In [1]:
import numpy as np

lista = [1,2,3,4]
print(type(lista))

np_lista = np.array(lista)
print(type(np_lista))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
a = [2,3,4]

a_dobrado = [x * 2 for x in a]
print (a_dobrado)

[4, 6, 8]


In [3]:
a = [2,3,4]

np_a = np.array(a)
np_a_dobrado = np_a * 2
print(np_a_dobrado)


[4 6 8]


In [4]:
print(np_a_dobrado.mean())

6.0


In [5]:
print(np_a_dobrado.max())

8


In [6]:
print(np_a_dobrado.min())

4


In [14]:
import numpy as np
anos_de_nascimento = np.loadtxt("nascimentos.txt")
idades = 2024 - anos_de_nascimento
print(f"A soma das idades é {idades.sum()}" )
print(f"A média das idades é {idades.sum()/idades.size}" )
print(f"A média das idades é {idades.mean()}" )
print(f"A média das idades é {np.average(idades)}" )
print(f"A forma é {np.shape(idades)}" )
print(f"Essa matriz possui {np.ndim(idades)} {'dimensões' if np.ndim(idades) > 1 else 'dimensão'}" )


A soma das idades é 213.0
A média das idades é 42.6
A média das idades é 42.6
A média das idades é 42.6
A forma é (5,)
Essa matriz possui 1 dimensão


In [20]:
# A estrutura usando nd_array, feita em numpy deve ser homogênea

a = [1,2,3, "string"]
print(a)

# Se houver string ele converte todos para string
b = np.array(a)
print(b)

[1, 2, 3, 'string']
['1' '2' '3' 'string']


In [28]:
import numpy as np
import time


inicio = time.time()
total = 10000
lista_python = range (total)
print (lista_python)
for i in range(total):
    resultado = [x * 2 for x in lista_python]
print(time.time() - inicio)

inicio = time.time()
np_array = np.arange(total)
for x in range(total):
    np_array *= 2
print(time.time() - inicio)



range(0, 10000)
5.9658284187316895
0.0725698471069336


In [29]:
# para criar direto tem que informmar apenas um argumento, no caso uma lista com colchetes
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [36]:
import numpy as np

# Criando um array a partir de uma lista
lista = [1, 2, 3, 4, 5]
arr1 = np.array(lista)
print("Array a partir de lista:", arr1)

# Criando um array usando arange
arr2 = np.arange(0, 15, 2)  # Números de 0 a 10 (exclusive) com passo 2
print("Array usando arange:", arr2)

# Reshape de um array
arr3 = arr2.reshape(4, 2)
print("Array após reshape:", arr3)

# Criando um array de zeros
arr_zeros = np.zeros((3, 3))  # Array 3x3 preenchido com zeros
print("Array de zeros:", arr_zeros)

# Ordenando um array
arr4 = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
arr_sorted = np.sort(arr4)
print("Array ordenado:", arr_sorted)

# Concatenando arrays
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
arr_concatenated = np.concatenate((arr5, arr6))
print("Arrays concatenados:", arr_concatenated)

# Convertendo um array para uma lista
arr7 = np.array([7, 8, 9])
lista_convertida = arr7.tolist()
print("Array convertido para lista:", lista_convertida)


Array a partir de lista: [1 2 3 4 5]
Array usando arange: [ 0  2  4  6  8 10 12 14]
Array após reshape: [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
Array de zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array ordenado: [1 1 2 3 3 4 5 5 5 6 9]
Arrays concatenados: [1 2 3 4 5 6]
Array convertido para lista: [7, 8, 9]


In [44]:
array_2d = np.array([[1,2], [3,4]])
print(array_2d)
print(f"array_2d[0][0]: {array_2d[0][0]}")
print(f"array_2d[0][1]: {array_2d[0][1]}")
print(f"array_2d[1][0]: {array_2d[1][0]}")
print(f"array_2d[1][1]: {array_2d[1][1]}")

[[1 2]
 [3 4]]
array_2d[0][0]: 1
array_2d[0][1]: 2
array_2d[1][0]: 3
array_2d[1][1]: 4


In [38]:
array_2d * 2

array([[2, 4],
       [6, 8]])

In [39]:
array_2d_2 = np.array([[1,2], [3,4]])
array_2d * array_2d_2

array([[ 1,  4],
       [ 9, 16]])

In [45]:
a = np.arange(64).reshape(16, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63]])

In [46]:
a.ndim

2

In [48]:
a.shape

(16, 4)

In [49]:
a.size

64

In [50]:
a.dtype

dtype('int32')

In [52]:
#array 3d
ddd = np.arange(60).reshape(3,4,5)
ddd

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [53]:
ddd.shape
# são 3 arrays (ndim) de 4 linhas e 5 colunas

(3, 4, 5)

In [56]:
s = ddd[ddd > 15]
s
# retorna um array unidimencional

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [68]:
zeros = np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
a = np.arange(2,30,2)
b = np.arange(2,30,3)
c = np.concatenate((a,b))
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28,  2,  5,  8,
       11, 14, 17, 20, 23, 26, 29])